# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vteacher/Lab4_4/Lab2.srcs/sources_1/ip/rom_d/rom_d.xci
# IP: The module: 'rom_d' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vteacher/Lab4_4/Lab2.gen/sources_1/ip/rom_d/rom_d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_d'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vteacher/Lab4_4/Lab2.srcs/sources_1/ip/rom_d/rom_d.xci
# IP: The module: 'rom_d' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vteacher/Lab4_4/Lab2.gen/sources_1/ip/rom_d/rom_d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_d'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
