# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vteacher/Lab5_23T/Lab5_23.srcs/sources_1/ip/ram_b/ram_b.xci
# IP: The module: 'ram_b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vteacher/Lab5_23T/Lab5_23.gen/sources_1/ip/ram_b/ram_b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vteacher/Lab5_23T/Lab5_23.srcs/sources_1/ip/ram_b/ram_b.xci
# IP: The module: 'ram_b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vteacher/Lab5_23T/Lab5_23.gen/sources_1/ip/ram_b/ram_b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
