# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/muxcst.xdc

# IP: ip/mux415_0/mux415_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux415_0 || ORIG_REF_NAME==mux415_0} -quiet] -quiet

# IP: ip/mux215_0/mux215_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mux215_0 || ORIG_REF_NAME==mux215_0} -quiet] -quiet
