# Project: bmpwork
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = bmp.o main.o
LINKOBJ  = bmp.o main.o
LIBS     = -L"E:/Dev-c++/Dev-Cpp/MinGW64/lib" -L"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = bmpwork.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

bmp.o: bmp.c
	$(CC) -c bmp.c -o bmp.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
